# Generated by Django 4.0.4 on 2022-05-13 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_app', '0002_alter_attendance_days_absents_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='days_absents',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='days_present',
        ),
    ]
